langauge: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
  - "node_modules"
branches:
  only:
    - "master"
install:
  - "yarn install"
  - "yarn run build"
script:
  - "echo \"No tests\""